#=CA Definitions

name: Rails Webserver CA
bits: 2048
dn:
 C: CH
 ST: Zurich
 L: Zurich
 O: RailsPKI
 OU: PKI
 CN: Rails Webserver CA
 
dn_policy:
 sort_as:
  - CN
  - OU
  - O
  - L
  - ST
  - C
 dn_info:
   C:
    - - match
      - _issuer
   ST:
    - - match
      - _issuer
   L:
    - - match
      - _issuer
   O:
    - - match
      - _issuer
   OU:
    - - supplied
      - _nil
   CN:
    - - supplied
      - _nil

extensions:
 default:
  basicConstraints:
   - true
   - CA:TRUE
  keyUsage:
   - true
   - keyCertSign, cRLSign
  subjectKeyIdentifier:
   - false
   - hash
  authorityKeyIdentifier:
   - false
   - keyid:always
  X509v3 CRL Distribution Points:
   - false
   - URI:https://railspki.rubyforge.org/certs/webserverca.crl
 sign:
  basicConstraints:
   - true
   - CA:FALSE
  keyUsage:
   -
  extendedKeyUsage:
   - false
   - serverAuth, clientAuth
  issuerAltName:
   - false
   - issuer:copy
  subjectAltName:
   - false
   - DNS:CN

#=EOF
